### ISSUE TITLE
Which version of the kwikset lock are you using?

### ISSUE THREAD

**Issue by JockDaRock** [RandomWireTechnologies/KeyforallEdison#1]
Hello,
I love your tutorial.  I almost have it working, lol. I am having a problem with the serial port staying connected due to an I/O error. The unlock clears just fine and unlocks the door.  when I issue the following lock command, I get the I/O error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lock_api.py", line 61, in unlock
    ser.write(kwikset.generate_unlock_packet())
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 383, in write
    n = os.write(self.fd, d)
OSError: [Errno 5] Input/output error
```

But I wanted to ensure I had the correct pinout as my kwikset lock looks a little bit different than yours.

Other information.  I ported this to Arduino Yun instead of the Edison and I am using the Kwikset 909 lock which is Home Connect ready.

Any thoughts you might have would be great.  I would like to start by making sure the lock's pinouts are the same.

Kind Regards,
Jock

**Comment by JockDaRock** [comment]
Actually, never mind.  I solved the problem with a minor workaround.  It ended up being the code 😄
